twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        app_name: '%env(APP_NAME)%'
        app_organization: '%env(APP_ORGANIZATION)%'
        app_site: '%env(APP_SITE)%'
        userSettings: '@App\Services\UserManagement\UserSettings'
        openingStatus: '@App\Services\SiteManagement\SiteSettings'
        portal: '%portal%'
        
    form_themes: ['bootstrap_5_layout.html.twig'] # +13/10/2022 : ajout de bootstrap
when@test:
    twig:
        strict_variables: true
