vich_uploader:
    db_driver: orm
    metadata:
        type: attribute # +13/10/2022 - php 8

    mappings:
        document_content:
            uri_prefix:         "%vich.path.document_content%" # le chemin web pour le répertoire
            upload_destination: "%kernel.project_dir%/public/doc" # répertoire de stockage des fichiers de ce service
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

