monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - ldap # +19/01/2023
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        nested:
            type: stream
            #path: php://stderr # -19/01/2023
            path: "%kernel.logs_dir%/%kernel.environment%/prod.log" # +19/01/2023
            level: debug
            #formatter: monolog.formatter.json # -19/01/2023
            formatter: monolog.formatter.line # +19/01/2023
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        ldap_logging:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%/ldap.log"
            max_files: 2
            level: debug
            channels: ["ldap"]
            formatter: monolog.formatter.line
